### ISSUE TITLE
这个项目应该如何运行？

### ISSUE THREAD

**Issue by sunpy1106** [striver-ing/wechat-spider#1]
python新手，看不懂代码。。。

**Comment by Boris-code** [comment]
需要 webppy， anyproxy

**Comment by sunpy1106** [comment]
谢谢，希望作者改天得空把readme完善下。。。

**Comment by wh4930188** [comment]
替换文件
node_modules\anyproxy\lib\rule_default.js
这也就不太清楚

**Comment by hdabing** [comment]
需要的webppy， anyproxy等环境搭建好了，修改数据库配置文件后，怎么运行项目代码，启动webppy报错

**Comment by Apokar** [comment]
老哥 加你群通过一下
