### ISSUE TITLE
Redis Error: Exception: Command #1 (ZADD wechat_spider:z_article_task ... ...) of pipeline caused error: value is not a valid float

### ISSUE THREAD

**Issue by XiangYu0777** [striver-ing/wechat-spider#15]
错误信息：Exception: Command # 1 (ZADD wechat_spider:z_article_task http://mp.weixin.qq.com/s?__biz=MzU0MDg5MTY0NA==&mid=2247499345&idx=2&sn=55f0ff35f6fe8838e84c2cdc653dab60&chksm=fb30fec2cc4777d4506743d91810053e5049441a726b476a10d89d10c4d6ada7001f0339de77&scene=27#wechat_redirect article_url) of pipeline caused error: value is not a valid float

在抓取文章详情时出现
![image](https://user-images.githubusercontent.com/17866337/68180259-07c1d480-ffce-11e9-8b97-72923503d09e.png)

系统和及软件信息：
Mac: 10.14.2 (18C54)
Python3: 3.7.4
MySql: 5.6
Redis: 3.2.13

现在初略估计是数据存储结构的问题

**Comment by Boris-code** [comment]
按章 redis&nbsp;&nbsp;2.10.6,&nbsp;
pip install redis==&nbsp;2.10.6




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Yu Xiang"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月5日(星期二) 中午1:14
收件人:&nbsp;"striver-ing/wechat-spider"<wechat-spider@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[striver-ing/wechat-spider] Redis Error: Exception: Command #1 (ZADD wechat_spider:z_article_task ... ...) of pipeline caused error: value is not a valid float (#15)




错误信息：Exception: Command # 1 (ZADD wechat_spider:z_article_task http://mp.weixin.qq.com/s?__biz=MzU0MDg5MTY0NA==&amp;mid=2247499345&amp;idx=2&amp;sn=55f0ff35f6fe8838e84c2cdc653dab60&amp;chksm=fb30fec2cc4777d4506743d91810053e5049441a726b476a10d89d10c4d6ada7001f0339de77&amp;scene=27#wechat_redirect article_url) of pipeline caused error: value is not a valid float
 
在抓取文章详情时出现
 
 
系统系统：
 Mac: 10.14.2 (18C54)
 Python3: 3.7.4
 MySql: 5.6
 Redis: 3.2.13
 
现在初略估计是数据存储结构的问题

**Comment by XiangYu0777** [comment]
@Boris-code 按照你说的方式重装 redis 依赖后，可以正常运行了👍
