### ISSUE TITLE
is_zombie 为 NULL 时，get_account_task 查不出数据

### ISSUE THREAD

**Issue by smilezheng** [striver-ing/wechat-spider#16]
在 task_manager.py 中 get_account_task 方法中的 sql 的条件多加一条
(
    (`is_zombie` != 1)
    OR (`is_zombie` IS NULL)
)

**Comment by Boris-code** [comment]
thanks

**Comment by Boris-code** [comment]
> 在 task_manager.py 中 get_account_task 方法中的 sql 的条件多加一条
> (
> (`is_zombie` != 1)
> OR (`is_zombie` IS NULL)
> )

默认值是0， 正常情况没null

**Comment by smilezheng** [comment]
> > 在 task_manager.py 中 get_account_task 方法中的 sql 的条件多加一条
> > (
> > (`is_zombie` != 1)
> > OR (`is_zombie` IS NULL)
> > )
> 
> 默认值是0， 正常情况没null

我的 account_task 数据是通过程序入的，所以出现 NULL 了😂
